[auth.email.template.confirmation]
subject = "Verify your Nexus account"
content_path = "./templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your Nexus password"
content_path = "./templates/recovery.html"

[functions.google-calendar]
verify_jwt = false
